### ISSUE TITLE
Disable Shop is busy command

### ISSUE THREAD

**Issue by Vidhin05** [Beez0r/iShop#11]
Is there a way to disable shop is busy message and allow multiple transactions at the same time?

**Comment by Vidhin05** [comment]
I get that you implemented a sort of lock but maybe it would be more convenient if it threw an error when the block being traded is not present when the final trade takes place. Useful when there are more shops/more people🤔

**Comment by Beez0r** [comment]
The way it is currently implemented is the only guaranteed method to prevent duping items by both shop owners and trading players

**Comment by Vidhin05** [comment]
What if it rather allows them to open the shop but not to buy items?

**Comment by Vidhin05** [comment]
Like if it shows shop busy when 
A. Shop restocking 
B. Another person just clicked buy and that transaction hasn't been processed yet.

**Comment by Beez0r** [comment]
For better performance, async tasks are used for almost all database accesses to not slow down the main thread, so that must be kept in mind. Feel free to open a pull request with feature implementations and I will test them out against all dupes and bugs.

Currently, there is no plan to change more than 1 player accessing shops of a single owner at a time due to the many issues that arise doing so and since there are no issues with current implementation.
