### ISSUE TITLE
Regarding issue #8 about shops disappearing, how do I uncorrupt a corrupted database?

### ISSUE THREAD

**Issue by Vidhin05** [Beez0r/iShop#12]
**Plugin Version and Minecraft Version**:

Latest iShop version, 1.16.5
**Describe the Bug, Duplication, or Problem**:
Shops wont be there, but stock is there
**How To Reproduce**:
cronjob to /restart and shops gone

**Comment by Beez0r** [comment]
If stock is still there but shops are missing, it sounds exactly the issue of (2) in issue #8 with problems using /restart command.

After you fix your startup script and follow recommendations listed in issue #8 then your shops and stock will start saving correctly. **Unfortunately there is no way to recover shops from corrupted databases, which is why backups are very important!** If you have backups, programs that can edit/modify the database exist such as DB Browser. I can help you with that if you attach files here.

**Comment by Vidhin05** [comment]
Gotcha, I had a 3 day old backup which I restored after removing the auro startup script.
