### ISSUE TITLE
Add hoppers support for adding to stock blocks.

### ISSUE THREAD

**Issue by OmegaMetor** [Beez0r/iShop#9]
**Plugin Version and Minecraft Version**: MC: 1.16.4 Plugin: 2.11

**Request**: Can you make it so that running a hopper into a stock block will automatically put the items from the hopper into the players stock?

**Reason**: This would make it easier for players with large farms to be able to keep their stock up better, without them needing to refill it manually. This would be very useful for players with highly efficient farms, because those can fill up large storages quickly, which would be difficult to add it all to the players stock.

**Additional Context**: None.

**Comment by Beez0r** [comment]
Shop and stock are accessed by using player UUID's. Unfortunately, using a hopper or anything not a player to access a players stock via the database is not currently possible, the stock block is universal and the player accessing it unlocks it by their UUID. It would only cause more issues such as other players using the hoppers to fill or add any items they want to stock that is not theirs. Also issues with our anti-duping system as well because feeding items into stock would render the shops busy until all stock transactions and database accesses are complete.

What players in my server have done to overcome trading vast amounts of items is add shulkers full of items to trade and fill up stock with those shulkers. Another option is to increase the stock page limit to whatever deemed necessary, as there is no limit on what can be set. You could have over 1000 pages of stock and access specific stock pages with /shop stock < page number >

Sorry, I don't believe this feature request is currently possible given the way this plugin is coded.
